flow_config:
        flow_params:
                mu: 1E-3
                rho: 1.
                inflow: "constant"
        geometry_params:
                #mesh: "mesh_files/cylinder_mesh_files/cylinder0.1000_0.05000_triangle.xdmf"
                mesh: "mesh_files/cylinder_mesh_files/cylinder0.1000_0.05000_triangle.xdmf"
        solver_params:
                dt: 0.001
                solver_type: 'lu'
                smooth: True
agent_params:
        solver_steps: 5000
        #solver_steps: 500
        episodes: 1000000
        timesteps: 10000
        threshold: 0.001 # Final drag about 0.1% different
        N_closest: 200
        gt_drag: -1
        gt_time: -1
        u: -1
        p: -1
        do_nothing: True
        time_reward: 0.005
        smoothing: True
        save_steps: 500
        #save_steps: 50

nn_params:
        layers: [128, 128, 128]
        activation: 'relu'
        dropout: 0.1
optimizer:
        name: 'adam'
        lr: 1e-3
        weight_decay: 1e-6


