flow_config:
        flow_params:
                mu: 1E-3
                rho: 1.
                inflow: "constant"
                #inflow: "1.0"
        geometry_params:
                mesh: "mesh_sweep/square_xdmf_files/square0.1000_0.05000_triangle.xdmf"
        solver_params:
                dt: 0.001
                solver_type: 'lu'
agent_params:
        solver_steps: 5000
        #solver_steps: 5
        episodes: 100000
        timesteps: 500
        threshold: 0.0001 # Final drag about 0.1% different
        N_closest: 100
        gt_drag: -1
        gt_time: -1
        u: -1
        p: -1
        do_nothing: False
        time_reward: 0

nn_params:
        layers: [128, 128, 128]
        activation: 'relu'
        dropout: 0.1
optimizer:
        name: 'adam'
        lr: 1e-3
        weight_decay: 1e-6


