flow_config:
        flow_params:
                mu: 1E-3
                rho: 1.
                inflow: "constant"
        geometry_params:
                mesh: "mesh_files/airfoil_mesh_files/ys930_0.15000_triangle.xdmf"
        solver_params:
                dt: 0.001
                solver_type: 'lu'
                smooth: True
agent_params:
        solver_steps: 5000
        #solver_steps: 500
        episodes: 1000000
        #episodes: 20
        timesteps: 10000
        threshold: 0.001 # Final drag about 0.1% different
        #threshold: 0.00075 # Final drag about 0.1% different
        #N_closest: 200
        N_closest: 180
        gt_drag: -1
        gt_time: -1
        u: -1
        p: -1
        do_nothing: True
        time_reward: 0.005
        smoothing: True
        #save_steps: 5000
        save_steps: 1000
        #save_steps: 500
        save_steps: 100
        goal_vertices: 0.9
        surrogate_threshold: 1e-5
        surrogate_range: [10,20]
        sur_drags: []
        sur_lifts: []
        mean_x: []
        mean_y: []
        std_x: []
        std_y: []
        model: None

nn_params:
        layers: [128, 128, 128]
        activation: 'relu'
        dropout: 0.1
optimizer:
        name: 'adam'
        lr: 1e-3
        weight_decay: 1e-6


